### ISSUE TITLE
Option to turn off weather bot notifications

### ISSUE THREAD

**Issue by jess192** [roboto84/wh00t_client#3]
A great enhancement to wh00t_client would be the option to turn off weather notifications.

**Comment by roboto84** [comment]
Agreed.  It would be great to build out the weather bot from air_bot to receive requests for weather information, as oppose to giving a weather update every hour on the chat.  Wh00t server acts as a chat and messaging service, so those bot messages may be of importance to other bots listening on the same wh00t server channel.  A good start to not deal with these time interval bot messages would be to maybe introduce a debug mode in the client for now which will show these messages in the chat only when the client is set to debug mode.  This will work until I have a chance to update the bots to handle these messages better.  Perhaps in the future, some sort of hierarchy of how different message types are handled may be something worth building out.  For now, let us try this and see what we think of the functionality.
